<a href="https://colab.research.google.com/github/hrittik2002/ML-Notes/blob/main/numpy/2_Array_Indexing_and_Slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

# 1. Numpy Indexing and Slicing of Vectors

## A. 1-D Array

In [3]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [4]:
## to print the index
arr[2]

np.int64(13)

In [5]:
arr[1:5] # start index : end+1 index

array([12, 13, 14, 15])

In [6]:
arr[:5] # default start value is 0

array([11, 12, 13, 14, 15])

In [7]:
arr[:] # default start value(0):default end value(size of arr)

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [8]:
arr[3:] # default end (size of arr)

array([14, 15, 16, 17, 18, 19, 20])

In [10]:
arr[1::2] # the 3rd vaiable is step
# start index = 1
# end index = size of arr
# step = 2

array([12, 14, 16, 18, 20])

## B. 2-D Array

In [3]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [4]:
arr[0] # print the 0th row

array([1, 2, 3, 4, 5])

In [5]:
arr[1][2] # print the 2nd element of 1st row

np.int64(8)

In [6]:
arr[1,2] # same think diff syntax

np.int64(8)

#### Slicing in 2D array


```
Print
2 3
7 8
from the array
```

here we are targeting the

0th and 1st row

1st and 2nd col




In [7]:
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])



```
Q. Print
19 20
24 25
29 39
from the 2D array arr
```



In [8]:
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])



```
Q. Print the second column
```



In [10]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

# 2. Boolean Indexing

In [12]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])



```
Q. Remove all the odd numbers from this array
```




In [14]:
bool_index = arr % 2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [16]:
arr[bool_index]

array([12, 14, 16, 18, 20])