<a href="https://colab.research.google.com/github/hrittik2002/ML-Notes/blob/main/numpy/3_array_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Array Operations

## 1. Arithmetic Operations

In [7]:
a1 = np.array([1, 2, 3, 4, 5])
a2 = np.array([6, 7, 8, 9, 10])
a1,a2

(array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10]))

In [8]:
a1 + a2

array([ 7,  9, 11, 13, 15])

This operations are called element-wise operation.


```
a1 = [1,  2,  3,  4,  5]
a2 = [6,  7,  8,  9, 10]
      +   +   +   +   +
   = [7,  9, 11, 13, 15]
```

In maths terms — yes, it's exactly like vector addition. Two vectors of same size, add element by element.

This is actually the core idea behind why numpy is so powerful for ML:

Normal Python list + would just concatenate → [1,2,3,4,5,6,7,8,9,10]

Numpy array + does math → element-wise addition



In [9]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [10]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [11]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [12]:
a1 // a2

array([0, 0, 0, 0, 0])

In [13]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

In [20]:
mat = np.arange(1,26).reshape(5,5)
mat, a1

(array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25]]),
 array([1, 2, 3, 4, 5]))

In [19]:
mat + a1 # add in all col

array([[ 2,  4,  6,  8, 10],
       [ 7,  9, 11, 13, 15],
       [12, 14, 16, 18, 20],
       [17, 19, 21, 23, 25],
       [22, 24, 26, 28, 30]])

## 2. Broadcasting


In [16]:
arr = np.array([10, 20, 30, 40])
arr + 10

array([20, 30, 40, 50])

You added a single number (scalar) to an array of 4 elements. Numpy automatically broadcasts (stretches) that 10 across all 4 positions.

In normal Python this wouldn't work, it will give typeerror


```
[10, 20, 30, 40] + 10  # ❌ TypeError
```

Numpy makes it work by internally imagining 10 as [10, 10, 10, 10] — without actually creating that in memory. So it's also memory efficient.




##

## 3. Deep Copy and Shallow Copy

In [21]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [23]:
b=a
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [26]:
b[0]=10
b , a

(array([10,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20]),
 array([10,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20]))

b = a did NOT create a copy. Both b and a point to the same memory location.

This is a shallow copy (actually even shallower — it's just an alias/reference).

### The difference
Deep copy means b will create a independent object in the memory


```
b = a.copy()
a -> 10   b -> 10

```


Swallow copy means b will just point to memory location of object of a


```
b = a
a -> 10 <- b

```


> Alwayse use .copy() for deep copy



In [29]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [30]:
b=a.copy()

In [31]:
b[0]=10
b , a

(array([10,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20]),
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20]))

## 4. Matrix Operations

### A. Matrix multiplication (dot product)



```
A = [[1,2],   B = [[5,6],
     [3,4]]        [7,8]]

Row × Column:
[0,0] = (1×5) + (2×7) = 5  + 14 = 19
[0,1] = (1×6) + (2×8) = 6  + 16 = 22
[1,0] = (3×5) + (4×7) = 15 + 28 = 43
[1,1] = (3×6) + (4×8) = 18 + 32 = 50

Result = [[19, 22],
          [43, 50]] ✅
```



In [35]:
A = np.array([[1,2] , [3,4]])
B = np.array([[5,6] , [7,8]])
A,B

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [39]:
A @ B # dot product (we can also write np.dot(A,B))

array([[19, 22],
       [43, 50]])

In [37]:
A * B # This is element wise multiplication

array([[ 5, 12],
       [21, 32]])

### B. Transpose of Matrix

In [40]:
A

array([[1, 2],
       [3, 4]])

In [41]:
A.T

array([[1, 3],
       [2, 4]])

In [45]:
C = np.array([[1,2,3],[4,5,6]])
C

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
C.T

array([[1, 4],
       [2, 5],
       [3, 6]])

## 5. Array Manipulation

### A. Stacking Array
Here we cant use matrix, we can only use vectors(1D array)

In [49]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
a,b

(array([1, 2, 3, 4]), array([5, 6, 7, 8]))

In [50]:
# 1. vertical stack
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [51]:
# horizonatl stack
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [52]:
# column stack
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

### B. Splitting Array

In [53]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [54]:
# horizontal split
np.hsplit(c,2) # we can do in 1,2,4 (for other -> error)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [55]:
# horizontal split
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]