<a href="https://colab.research.google.com/github/hrittik2002/ML-Notes/blob/main/numpy/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

# 1. The Problem with Python list Data Structure

Python was designed to be flexible. A list can hold anything:


In [2]:
my_list = [1, "hello", True, 3.14, None]  # totally valid

Under the hood, a Python list is an array of pointers. Each element is a separate **Python Object** sitting somewhere in memory and the list just holds addresses pointing to those objects. Each Python object also carries extra baggage — its type info, reference count for garbage collection, etc.

A single integer 1 in a Python list takes 28 bytes in memory. And those objects are scattered randomly across RAM.

## Now think about ML for a second:

A grayscale image that is 1920×1080 pixels = 2,073,600 numbers. A dataset of 10,000 such images = 20 billion numbers. You need to do math on all of them — multiply, add, average — thousands of times during training.

With a Python list you'd write:

In [4]:
# multiply every pixel by 2
# result = [x * 2 for x in pixels]

# 2. What NumPy does differently — three fundamental things:

## 1. Homogeneous type
A NumPy array holds one type only. You declare it upfront:


In [5]:
# import numpy as np
# arr = np.array([1, 2, 3, 4, 5], dtype=np.float64)

Now NumPy knows every element is a float64 — 8 bytes, no exceptions. No need to check type per element ever again.

## 2. Contiguous memory

All values sit side by side in RAM like seats in a row:


In [6]:
# RAM: [1.0][2.0][3.0][4.0][5.0]
#      8b    8b   8b   8b   8b

Your CPU has a cache — it loads 64 bytes at a time (called a cache line). With NumPy, one cache load gives you 8 floats ready to process. With a Python list, each element is a pointer to somewhere else in RAM — every access is a cache miss.

## 3. Vectorized operations in C

Numpy is written in C. NumPy doesn't loop in Python at all. It calls a pre-compiled C function that uses SIMD instructions — special CPU instructions that multiply 4 or 8 numbers simultaneously in one clock cycle.



# 3. Basic Array Creation

In [8]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [9]:
## list looks different
a = [1,2,3,4]
a

[1, 2, 3, 4]

Numpy arrays are in homogeneous in nature. There can be only one data type in the numpy array.
Example:

In [10]:
# In case of python list we can store multiple data type's in a single array
a = [1, 2, 3, 4.5, "Hello"]
a

[1, 2, 3, 4.5, 'Hello']

In [11]:
# But when we are makeing a numpy array out of the list a, all the emements are becoming string
np.array(a)

array(['1', '2', '3', '4.5', 'Hello'], dtype='<U32')

In [13]:
np.array([1, 3, 6.2]) # now all will be converted to float

array([1. , 3. , 6.2])

## 2-D Array or Matrix


In [14]:
np.array([[1,2,3],[3,4,5],[6,7,8]])

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

> ### What is tensor?
>
> A tensor is just an array of numbers with a shape.
> - In NumPy → called **ndarray** (n-dimensional array)
> - In PyTorch / TensorFlow → called **Tensor**
>
> Same concept, different name. Tensor is the ML world's word for ndarray.

# 4. Array Generation Function

## a. arange

This is used for generating an array within a range

In [3]:
# This prints all the number from 1 to 10(11-1)
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
# We can put step variable too
arr = np.arange(1,11,2) # now it will increase by 2
arr

array([1, 3, 5, 7, 9])

## b. zeros

to generate arrays or ndarray of 0.

In [13]:
arr = np.zeros(5) # array of 0 of len=5
arr

array([0., 0., 0., 0., 0.])

In [14]:
arr = np.zeros((2,3)) # array of 0 of shape(2,3)
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

## c. ones

array of ones

In [18]:
arr = np.ones((3,7))
arr

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

## d. linspace
to generate an array of evenly spaced numbers over a specified interval

In [21]:
arr = np.linspace(0,10,3)
# print vector of 3 number with equal space btw 1 to 10
arr

array([ 0.,  5., 10.])

In [23]:
arr = np.linspace(0,1,10) # 10 number btw 0 and 1
arr

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

# 5. Random Generation Function

In [24]:
np.random.rand(10)
# Gives numbers between 0 and 1 only
# Every number has equal chance (uniform distribution)
# Think of it like: "random percentage values"


array([0.41567315, 0.08934897, 0.70298153, 0.58469347, 0.51328832,
       0.35497156, 0.51530916, 0.2199594 , 0.84523596, 0.53225362])

In [25]:
np.random.randn(10)
# Gives numbers around 0, can be negative
# Follows a bell curve (normal/Gaussian distribution)
# Most values stay between -3 and +3, but no hard limit
# Think of it like: "random values centered at zero"

array([-2.08783233,  0.8394111 , -0.65946113,  0.66269508,  0.50228816,
        0.16692041, -1.14167105, -1.28853211,  0.28535988, -0.83081787])

In [27]:
np.random.randint(10,20,7)
# Gives whole numbers only (integers)
# Between a min and max you define — here 10 to 20
# Third argument 7 = how many numbers to generate
# Think of it like: "random dice rolls in a range"

array([10, 15, 11, 10, 12, 13, 12])

# 6. Array Attributes

In [48]:
# lets defin a array
arr = np.array([[1,2,3,5],[4,5,6,3],[7,8,9,11]])
arr

array([[ 1,  2,  3,  5],
       [ 4,  5,  6,  3],
       [ 7,  8,  9, 11]])

When you create an array, NumPy gives it a shape.
That shape is a tuple like (3,) or (3, 4) or (2, 3, 4).
Each position in that touple is one axis.

```
arr.shape = (2, 3, 4)
#            ↑  ↑  ↑
#           [0][1][2]   ← these are the axis numbers
```
For a 1-D array


```
axis 0 →  [10, 20, 30, 40, 50]
shape=(5,)
```
For a 2-D array


```
axis 1 →→→→
         col0 col1 col2 col3
axis  ↓  [ 1,  2,  3,  4]   row 0
  0   ↓  [ 5,  6,  7,  8]   row 1
      ↓  [ 9, 10, 11, 12]   row 2

# shape → (3, 4)
#          ↑  ↑
#        ax0  ax1
#         3   4  ← 3 rows, 4 columns
```

For a 3-D array



```
Block 0 (page 1):          Block 1 (page 2):
[[ 1,  2,  3,  4],         [[ 13, 14, 15, 16],
 [ 5,  6,  7,  8],          [ 17, 18, 19, 20],
 [ 9, 10, 11, 12]]          [ 21, 22, 23, 24]]

axis 0 → which page/block (depth)
axis 1 → which row (within a page)
axis 2 → which column (within a row)

# shape → (2, 3, 4)
#          ↑  ↑  ↑
#        ax0 ax1 ax2
#         2   3   4
#         |   |   └── 4 columns
#         |   └────── 3 rows
#         └────────── 2 blocks (like 2 pages/layers)
```











In [43]:
arr.shape # it prints the shape of the array

(3, 4)

In [45]:
arr.size # total no of elements in array

12

In [44]:
arr.dtype # data type of elements of array

dtype('int64')

# 7. Array Methods

In [49]:
arr

array([[ 1,  2,  3,  5],
       [ 4,  5,  6,  3],
       [ 7,  8,  9, 11]])

In [50]:
arr.min() # min element in arr

np.int64(1)

In [51]:
arr.max() # max element in arr

np.int64(11)

In [52]:
arr.sum() # sum of all elements

np.int64(64)

In [53]:
np.sum(arr,axis=1)

array([11, 18, 35])

Here,

axis=1 — collapse
the columns dimension

You travel sideways through all the columns and combine them.
Each row produces one output value.

In [54]:
np.sum(arr,axis=0)
# collapse axis 0

array([12, 15, 18, 19])

In [55]:
arr.mean() # mean

np.float64(5.333333333333333)

In [57]:
arr.std() # standard deviation

np.float64(2.8674417556808756)

In [58]:
arr.argmax() # index of max element

np.int64(11)

In [59]:
arr.argmin() # index of min element

np.int64(0)

# 8. Reshaping and Resizing

In [61]:
arr = np.arange(1,31) # 30 elements
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [63]:
# we need to give the shape in with we want to reshape
arr.reshape(6,5) # 6x5=30 elements

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [64]:
arr.reshape(3,10) # 3x10=30 elements

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [67]:
arr.reshape(2,2) # 2x2=4 elements
# error as we cant put 30 elements in arrar of size 4

ValueError: cannot reshape array of size 30 into shape (2,2)